global:
  scrape_interval:     15s
  evaluation_interval: 15s
     
rule_files:
  - "/etc/prometheus/alert.rules"
  # - "first.rules"
  # - "second.rules"

alerting: 
 alertmanagers: 
 - static_configs: 
   - targets: 
     - alertmanager:9093
    
scrape_configs:
  - job_name: prometheus
    static_configs:
     - targets: ['localhost:9090']
  - job_name: cadvisor
    static_configs: 
     - targets: 
       - cadvisor:8080
  - job_name: node_exporter
    static_configs:
     - targets: [node_exporter:9100]
  - job_name: apache_exporter
    static_configs: 
     - targets: 
       - 165.227.113.136:9117
  - job_name: debian_node_exporter
    static_configs:
     - targets:
       - 165.227.113.136:9100
  - job_name: wmi_exporter
    static_configs: 
     - targets: 
       - 179.181.198.15:9182
  - job_name: snmp
    static_configs:
     - targets:
       - 127.0.0.1  # SNMP device.
       - 179.181.198.15
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 165.227.113.136:9116  # The SNMP exporter's real hostname:port.
 
